prog:menu.o main.o 
	gcc menu.o main.o -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -o jeux
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
menu.o:menu.c
	gcc -c menu.c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
